# Generated by Django 6.0.6 on 2026-06-06 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('LUMINARIA', 'Luminária'), ('AR_CONDICIONADO', 'Ar-condicionado')], max_length=30)),
                ('status_atual', models.CharField(choices=[('OPERANDO', 'Operando'), ('DEFEITO', 'Defeito'), ('MANUTENCAO', 'Manutenção')], default='OPERANDO', max_length=30)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerimetroGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('coordenadas', models.JSONField(help_text='Lista de pontos latitude/longitude do polígono')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sala', models.CharField(max_length=50, unique=True)),
                ('bloco', models.CharField(max_length=100)),
                ('andar', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_problema', models.TextField()),
                ('status_chamado', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=30)),
                ('data_hora_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_hora_fechamento', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='core.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('acao_realizada', models.TextField()),
                ('tecnico_responsavel', models.CharField(blank=True, max_length=150, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='core.chamado')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='core.sala'),
        ),
        migrations.CreateModel(
            name='VerificacaoGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('dentro_perimetro', models.BooleanField(default=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('perimetro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes', to='core.perimetrogps')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes_gps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
