# Generated by Django 6.0.6 on 2026-06-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perimetrogps',
            name='coordenadas',
        ),
        migrations.AddField(
            model_name='perimetrogps',
            name='latitude_centro',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perimetrogps',
            name='longitude_centro',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perimetrogps',
            name='raio_metros',
            field=models.FloatField(default=50),
        ),
    ]
