# Generated by Django 6.0.6 on 2026-06-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_perimetrogps_coordenadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='posicao_x',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='posicao_y',
            field=models.FloatField(default=50),
        ),
    ]
