# Generated by Django 6.0.6 on 2026-06-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipamento_posicao_x_equipamento_posicao_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='predio',
            field=models.CharField(choices=[('PREDIO_PRINCIPAL', 'Prédio Principal'), ('COMPLEXO', 'Complexo')], default='PREDIO_PRINCIPAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='sala',
            name='andar',
            field=models.CharField(help_text='Ex: Térreo, 1º Andar, 2º Andar, 3º Andar', max_length=50),
        ),
        migrations.AlterField(
            model_name='sala',
            name='bloco',
            field=models.CharField(help_text='Ex: Bloco A, Informática, Auditório, Projeto Educa', max_length=100),
        ),
    ]
