# Generated by Django 6.0.6 on 2026-06-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sala_predio_alter_sala_andar_alter_sala_bloco'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=20),
        ),
    ]
