# Generated by Django 6.0.6 on 2026-06-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chamado_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='planta_altura',
            field=models.FloatField(default=8),
        ),
        migrations.AddField(
            model_name='sala',
            name='planta_largura',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='sala',
            name='planta_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sala',
            name='planta_y',
            field=models.FloatField(default=0),
        ),
    ]
